# Generated by cucumber-sinatra. (2013-12-10 23:35:23 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/waza101.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Spike

class SpikeWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SpikeWorld.new
end
